### PR TITLE
Early support for counts

### PR DESCRIPTION
**Pull request by rbuckton**
Related to #7

I started tinkering with how this might work, but unfortunately there doesn't seem to be any documentation on how to set up local support for functions.

This PR currently isn't intended to be merged, but to be discussed for feasibility.

### CODE REVIEW

**Comment by urish** [comment]
@rbuckton you can run the functions locally by running:

`yarn start:functions`

Is there anything else missing so you can test it?

**Comment by rbuckton** [comment]
Unfortunately it requires permissions I don't have:

```
C:\dev\bigtsquery [addCount ≡]> yarn start:functions
yarn run v1.9.4
$ firebase serve --only functions

Error: Unable to authorize access to project bigtsquery
```

**Comment by urish** [comment]
What is your google account email address? I will try to authorize you on this project.

**Comment by rbuckton** [comment]
It's the same as the email address on my GitHub profile.

**Comment by rbuckton** [comment]
I've amended the commit with some changes now that I can test. The query seems like it might be working, as http://localhost:5000/bigtsquery/us-central1/count?q=ClassDeclaration%3Ahas(ExportKeyword)%3Ahas(Decorator) returns the following:

```json
{"count":279943}
```

**Comment by rbuckton** [comment]
There's no UI associated with this at present, I can look into that later this week.

**Comment by urish** [comment]
Thank you!

A few notes:
1. Can you please remove the formatting changes in `package.json` and `src/package.json`? 
2. I see that you changed `functions/src/bigquery.d.ts`, where did you take the new version from?

And of course, a UI for this will be appreciated!

**Pull request closed without merging**
